* How to bypass pattern lock on Android if you have made `too many attempts`

/Note/: This is ONLY tested on Aakash but other may find these scripts
and reference useful

/Problem/: The attempt to unlock pattern was exceeded, so with no
Internet connection and adb access how to delete the database entries

/Solution/:

** Downloading and burning an image on SD-card
   + Buy one 8 GB SD-card and download GNU/linux image for Aakash from
     [[http://www.it.iitb.ac.in/AakashApps/repo/GNU-Linux-on-Aakash/12.10-lxde-bootLogo-0secUboot-expeyes-scilab-on-cloud-sleep1.img.bz2][here]]. 

   + Extract that image using the command
     #+BEGIN_SRC bash
     tar -xvjf 12.10-lxde-bootLogo-0secUboot-expeyes-scilab-on-cloud-sleep1.img.bz2
     #+END_SRC

   + You need to burn that extracted image to SD-card. Insert the
     SD-card in to the SD-card slot slot of your laptop/PC and run
     this command.

     #+BEGIN_SRC bash
     sudo dd if=12.10-lxde_with_scilab_on_cloud_cleaned.img of=/dev/sdb bs=1024
     #+END_SRC

     assuming your SD-card was detected as =/dev/sdb=

** Booting with GNU/linux image
   + Insert the SD-card in to the SD-card slot of the tablet and power
     and hold the /power/ button until you see Aakash's bootsplash
     screen.
     
** Installing required dependencies
   + You need to edit the settings.db file. This is sqlite's
     database. You may need to install =sqlite3= on the
     tablet(GNU/linux side). You can install it using =apt-get=. The
     command is 

     #+BEGIN_SRC bash
     sudo apt-get install sqlite3
     #+END_SRC

     If you decide to use the automated scripts from this directory,
     you may also need to install =python-pysqlite2= which python
     interface library for =sqlite3=. The command is

     #+BEGIN_SRC bash
     sudo apt-get install python-pysqlite2
     #+END_SRC
     
** Mounting the NAND partition

   + login as =root= 

     #+BEGIN_SRC bash
     sudo -s
     #+END_SRC

     give the password as =123=

   + Now you need to mount =/dev/nande= partition in which the
     =settings.db= file resides. 

   + Make a temporary directory

     #+BEGIN_SRC bash
     mkdir -p /root/nande
     #+END_SRC

     and mount the =nande= partition using the command

     #+BEGIN_SRC bash
     mount /dev/nande /root/nande
     #+END_SRC

** Update sqlite database
   + now change the directory where the =settings.py file resides=

     #+BEGIN_SRC bash
     cd nande/data/com.android.providers.settings/databases
     #+END_SRC

     and use the database

     #+BEGIN_SRC bash
     sqlite3 settings.db
     #+END_SRC

     /Make copy of original file just in case/

   + Now update the database

     #+BEGIN_SRC bash
     update secure set value=0 where name='lock_pattern_autolock';
     #+END_SRC

     #+BEGIN_SRC bash
     update secure set value=0 where name='lockscreen.lockedoutpermanently';
     #+END_SRC

     quit sqlite interface

     #+BEGIN_SRC bash
     .quit
     #+END_SRC
     
   + Also remove the gesture key file

     #+BEGIN_SRC bash
     rm /data/system/gesture.key
     #+END_SRC

   + Unmount the NAND partition

     #+BEGIN_SRC bash
     cd /root
     umount /dev/nande
     #+END_SRC

   + poweroff the tablet

     #+BEGIN_SRC bash
     poweroff
     #+END_SRC

   + Remove the SDcard and boot into Android

** Using scripts in this directory

   + Instead of following the above procedure, you can download or
     copy this directory to =/root= directory of the tablet(GNU/linux
     side) and simply execute the script file =pattern_unlock.sh=

     #+BEGIN_SRC bash
     cd unlock_android_pattern
     bash ./pattern_unlock.sh
     #+END_SRC

   + and restart the tablet removing the SD-card

** Additional commands(sqlite3)
   + View description of table
     
     #+BEGIN_SRC bash
     pragma table_info([table_name])
     #+END_SRC

     for example
     #+BEGIN_SRC bash
     pragma table_info([secure])
     #+END_SRC

   + list all the tables in the database

     #+BEGIN_SRC bash
     .tables
     #+END_SRC



FOR EDUCATIONAL PURPOSE ONLY!
